[package]
name = "zip-vmm"
version = "0.1.0"
edition = "2024"
description = "ZIP archive as a backing store for virtual memory (implementation)"
repository = "https://github.com/ButterflyCurtain/zip-virtual-memory-manager-impl"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
crc32c = "0.6"
getrandom = "0.2"
libz-rs-sys = "0.6.3"
memmap2 = "0.9.10"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
